### PR TITLE
update ansible script to works on buster

### PR DESCRIPTION
**Pull request by alexandrasp**
Adjustments to run ansible configuration scripts on
Debian Buster and build kernelci-backend locally or
in the place of your preference.

Signed-off-by: Alex P <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
I think it would be good to bring up a new staging backend server with Buster and test it with this Ansible config.  Then if it works, we can use it to replace the current one and do the same with production.

@mattface Do we have any plans server-wise to do that?

**Comment by alexandrasp** [comment]
@gctucker sure! I will update some details in ansible syntax and for your interest I am using a VM w/ Buster locally to test, ok ?

**Comment by gctucker** [comment]
Sure it's great that you can test this locally.  But we should also be using Debian Buster for the kernelci.org servers, and as we're currently using this Ansible config to do backend updates we will need to coordinate the server upgrade when merging this PR.

**Comment by alexandrasp** [comment]
working and all deprecated, like below, was removed.

> [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `pkg: "{{ item }}"`.

tested locally, the log file can be seen here: [Test result](https://people.collabora.com/~alex.pereira/tests/log-backend.txt).

After run that ansible script you will be able to access kernelci-backend with a local (or remote) server.

**Comment by gctucker** [comment]
Tested OK on staging.kernelci.org after upgrading to Buster. Ready to use in production on kernelci.org too which has also been upgraded to Buster.

**Pull request merged**
