### PR TITLE
git package is necessary for doing checkouting site

### PR DESCRIPTION
**Pull request by montjoie**

### CODE REVIEW

**Comment by MiloCasagrande** [comment]
The git dependency is already installed globally when you run the entire set of tasks (or through a subset of them).

It's in here:

https://github.com/kernelci/kernelci-backend-config/blob/master/roles/install-deps/tasks/main.yml

and you need all those dependencies to build the virtual environment as well.
What would be your use case for moving it here as well?

**Comment by montjoie** [comment]
Roles must be independant from each over, but perhaps you prefer that I add roles dependencies ?

**Comment by MiloCasagrande** [comment]
My question is more to understand why you only need the git dependency
there, and not all the python ones.

Even if you run just the single role to install the app, you still
need the python packages installed in order for the virtualenv
installation step to work, or it might not work correctly or as
expected.

The setup of the system is a single playbook that should be run in its
entirety the first time to correctly configure it (that's why most of
the packages are installed in a single role). The git package will be
installed and it will never be removed afterwards. At that point, the
system configuration is fixed.

Roles are used to group tasks together, the playbook tells you how
those roles should be applied.

-- 
Milo Casagrande
Linaro.org <www.linaro.org> │ Open source software for ARM SoCs

**Comment by montjoie** [comment]
It was just a simple pull request for testing the process. I agree, if git is set, virtualenv and co is necessary.
I will simply close this request, the best way is to set a role dependency

**Pull request closed without merging**
